### ISSUE TITLE
Encounter ModuleNotFoundError: yaml

### ISSUE THREAD

**Issue by octocatsup** [J4FSec/HaccTheHub#3]
Run the following command to start the backend after starting Docker Desktop (Compose and Desktop versions are installed and running):

```
python3 main.py
Traceback (most recent call last):
  File "/Users/$USER/HaccTheHub/backend/main.py", line 1, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

Receive the error above upon running this command. The previous steps completed with no issues.

**Comment by watch-dog-man** [comment]
@Cu64 Please review.
@octocatsup Thank for the post.

**Comment by Cu64** [comment]
Hi, sorry for the late response.
Apparently I forgot to include `pyyaml` as a requirement so can you please run `python3 -m pip install pyyaml` to install it and try again? I'll be updating the requirements.txt file shortly.
